version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - static_data:/vol/web
    - ./Tacotron_TTS:/tacotron_app
    environment:
      - ALLOWED_HOSTS=127.0.0.1,localhost

  nginx:
    build: ./nginx
    volumes:
    - static_data:/vol/static
    ports:
    - "8080:8080"
    depends_on:
      - api

volumes:
  static_data: