version: '3.7'

services:
  api_app:
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - ./Tacotron_TTS:/tacotron_app
    command: sh -c "ptyhon manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1